apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: app-votacion
  spec:
    type: ClusterIP
    ports:
    - port: 6379
      targetPorts: 6379
      name: "redis-service"
    selector:
      name: redis
      app: app-votacion
