apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result
    app: app-votacion
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPorts: 80
      NodePort: 31001
      name: "result-service"
    selector:
      name: result
      app: app-votacion