apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1-dp
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata: 
      name: app1-pod
      labels:
        app: app1
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 5
  selector:
    matchLabels:
      type: front-end
      app: app1