apiVersion: v1
kind: ReplicationController
metadata:
  name: app1-rc
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata:
      name: app1-pod
      labels:
          app: app1
          type: front-end
      spec:
          containers:
            - name: nginx-container
              image: nginx
  replicas: 2
